### PR TITLE
Radviz generalizations

### PR DESCRIPTION
**Pull request by Mahog**
Hi everyone, I talked to @MarkoAngelini earlier today about making some contributions to the RadViz plugin, to reuse it one of our research projects. This PR contains 5 commits that contribute the following changes: 

*  [```0480728```](https://github.com/aware-diag-sapienza/d3-radviz/commit/0480728b7ddb93ba301e4e5833e88f5dd879507d) ensures that the modularized version of radviz properly references the d3 library. Previously, it was assumed that the ```d3``` variable is part of the global namespace, i.e. d3 is imported as a separated ```<script/>``` element. When shipping d3-radviz as independent bundle, we need to import d3 as npm package. For simplicity, I imported the entire d3 module, rather than importing individual sub-packages for each function (let me know how you feel about this issue).

* [```35f9f799```](https://github.com/aware-diag-sapienza/d3-radviz/commit/35f9f7995524ea2ca9893b590a1b271ff69c0215) ensures a uniform indentation and line ending style across the project. It does so by adding two new rules to .eslintrc, which enforces that expressions should end with ```;``` and the tab-size is 4 and then applying them to all .js files of the project.

* [```db01b466a```](https://github.com/aware-diag-sapienza/d3-radviz/commit/db01b466a397254b710bab98999c36e8e5af892a)  allows computing the exact screen location of points on the canvas by adding d3-style getter/setter functions to radviz. The functions (1) allow getting the two scales used to place data along the ```x1``` and ```x2``` dimensions of entries. and (2) getting the offset of ```g#radviz-g-[id]```.

* [```99a14d84b```](https://github.com/aware-diag-sapienza/d3-radviz/commit/99a14d84bf337bd9c4483dfabc2ef6dd378277a4) enables using the radviz package in TypeScript projects. This is done by adding the type declaration file ```index.d.ts``` to src/ that describes the RadViz interface. TypeScript projects can now import the d3-radviz package with type safety at compile time.

* [```ee7f59c1a```](https://github.com/aware-diag-sapienza/d3-radviz/commit/ee7f59c1ad102c863f78b78077bc0084d3d89d80) adds documentation to the type declarations, using the wording from README.md.

### CODE REVIEW

**Comment by simone-lenti** [comment]
Hi @Mahog, sorry for the late reply. Thanks for your contribution, it is really welcomed.
I am absolutely in favor of accepting this PR; the only doubt is about the import of the entire d3 module, as I prefer importing individual packages to keep the size as small as possible. Your considerations about [0480728](https://github.com/aware-diag-sapienza/d3-radviz/commit/0480728b7ddb93ba301e4e5833e88f5dd879507d) are still valid, I'd rather just differentiate the imports. Let us know if it seems reasonable to you and if it can be directly addressed by you, otherwise I'll assign the task to one of us. I leave open the PR to resolve this point here, once done I think we can proceed to merge it.

**Review by simone-lenti — APPROVED** [review]

**Comment by Mahog** [comment]
I agree importing only submodules is the lightweight and better way to go, and I have made the changes in [576480f](https://github.com/aware-diag-sapienza/d3-radviz/pull/4/commits/576480fad38395685cdc9db155f8dd054d4b58ff). 

I see only one issue, which is the ```.on("contextmenu")``` event listener in radviz.js:80. I assume that it was originally intended to use the [d3-context-menu plugin](https://github.com/patorjk/d3-context-menu), but I can't find any references to that plugin anywhere in the project. In [576480f](https://github.com/aware-diag-sapienza/d3-radviz/pull/4/commits/576480fad38395685cdc9db155f8dd054d4b58ff), this part of the code is thus "dead". Can you comment on that?

**Comment by simone-lenti** [comment]
> I see only one issue, which is the `.on("contextmenu")` event listener in radviz.js:80. I assume that it was originally intended to use the [d3-context-menu plugin](https://github.com/patorjk/d3-context-menu), but I can't find any references to that plugin anywhere in the project. In [576480f](https://github.com/aware-diag-sapienza/d3-radviz/pull/4/commits/576480fad38395685cdc9db155f8dd054d4b58ff), this part of the code is thus "dead". Can you comment on that?

@alessia-palleschi can you give feedback on this?

**Comment by alessia-palleschi** [comment]
> I agree importing only submodules is the lightweight and better way to go, and I have made the changes in [576480f](https://github.com/aware-diag-sapienza/d3-radviz/pull/4/commits/576480fad38395685cdc9db155f8dd054d4b58ff).
> 
> I see only one issue, which is the `.on("contextmenu")` event listener in radviz.js:80. I assume that it was originally intended to use the [d3-context-menu plugin](https://github.com/patorjk/d3-context-menu), but I can't find any references to that plugin anywhere in the project. In [576480f](https://github.com/aware-diag-sapienza/d3-radviz/pull/4/commits/576480fad38395685cdc9db155f8dd054d4b58ff), this part of the code is thus "dead". Can you comment on that?

Hi @Mahog, 
I don't know the plugin, I just captured that event to add specific behavior. If you think it's useful, we can use the plugin, but I've never used it. Also, I don't understand the reference you give me radviz.js:80. 
It is the line `function_context_menu (data.angles);` which is an auxiliary function that allows the user to customize the default events connected with the radiviz.

**Comment by Mahog** [comment]
Sorry, I just realized that ```"contextmenu"``` is a standard DOM event for the click of the [right mouse button](https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event). I had never seen that one before, so sorry about the confusion.

Then there is no need for any additional plugins 👍 

Regarding the reference, I was referring to [line 80 in radviz.js](https://github.com/aware-diag-sapienza/d3-radviz/blob/576480fad38395685cdc9db155f8dd054d4b58ff/src/radviz.js#L80) on the radviz-generalizations branch.

**Comment by alessia-palleschi** [comment]
Ok perfect, no problems.

**Pull request merged**
